### PR TITLE
should fail if --define placeholder value doesn't match placeholder regex

### LINKED ISSUE #545: should fail if --define placeholder value doesn't match placeholder regex
For reference, the placeholder I am working with is here: https://github.com/waynr/proc-macro-template/blob/main/function-like/cargo-generate.toml

If I add `regex = "^$"` at the bottom of the file and let `cargo-generate` prompt me to enter the value I get:

```
zsh/3 3755 [130]  (git)-[main]-% cargo-generate generate --path function-like --name meow
⚠️   Unable to load config file: /home/wayne/.cargo/cargo-generate.toml
🔧   Generating template ...
🤷   What will the name of your macro be? : funky-bogus-macro
⚠️   Sorry, "funky-bogus-macro" is not a valid value for macro_name
```

On the other hand, using `--define` works fine:

```
zsh/3 3755 [130]  (git)-[main]-% cargo-generate generate --path function-like --name meow -d "macro_name=funky-bogus-macro"
⚠️   Unable to load config file: /home/wayne/.cargo/cargo-generate.toml
macro_name => 'funky-bogus-macro'
🔧   Generating template ...
[ 1/19]   Done: .gitignore
[ 2/19]   Done: Cargo.lock
[ 3/19]   Done: Cargo.toml
[ 4/19]   Done: src/lib.rs
[ 5/19]   Done: src/funky-bogus-macro/analyze.rs
[ 6/19]   Done: src/funky-bogus-macro/codegen.rs
[ 7/19]   Done: src/funky-bogus-macro/lower.rs
[ 8/19]   Done: src/funky-bogus-macro/mod.rs
[ 9/19]   Done: src/funky-bogus-macro/parse.rs
[10/19]   Done: src/funky-bogus-macro
[11/19]   Done: src
[12/19]   Done: tests/funky-bogus-macro/fail/invalid_syntax.rs
[13/19]   Done: tests/funky-bogus-macro/fail/invalid_syntax.stderr
[14/19]   Done: tests/funky-bogus-macro/fail
[15/19]   Done: tests/funky-bogus-macro/pass/valid_syntax.rs
[16/19]   Done: tests/funky-bogus-macro/pass
[17/19]   Done: tests/funky-bogus-macro/ui.rs
[18/19]   Done: tests/funky-bogus-macro
[19/19]   Done: tests
🔧   Moving generated files into: `/home/wayne/projects/waynr/proc-macro-template/meow`...
💡   Initializing a fresh Git repository
✨   Done! New project created /home/wayne/projects/waynr/proc-macro-template/meow
```

My expectation is that this should fail instead of proceeding to use an invalid placeholder value.

### PR DESCRIPTION
**Pull request by taurr**
Fixes #545

### CODE REVIEW

File: src/hooks/system_mod.rs [hunk 1]
```diff
@@ -45,17 +45,20 @@ fn run_command(
...
-            let value = prompt_for_variable(&TemplateSlots {
-                prompt,
-                var_name: "".into(),
-                var_info: VarInfo::String {
-                    entry: Box::new(StringEntry {
-                        default: Some("no".into()),
-                        choices: Some(vec!["yes".into(), "no".into()]),
-                        regex: None,
-                    }),
+            let value = prompt_and_check_variable(
```
Comment (taurr) [inline src/hooks/system_mod.rs:48]: Formatting due to fn name change!

**Comment by taurr** [comment]
Fixes #698

**Comment by taurr** [comment]
Closes #402 

ALL placeholder values, no matter where they come from goes through the validation now!
